### ISSUE TITLE
DiscreteLog algorithm choice

### ISSUE THREAD

**Issue by clementnuss** [ldsec/unlynx#19]
the [discreteLog function](https://github.com/lca1/unlynx/blob/master/lib/crypto.go#L310) in `lib/crypto.go` uses the naïve trial-and-error approach to compute the discrete logarithm of a Point.

Would it not be a better approach to use the baby-step giant-step algorithm ? This would also permit to have a greater `MaxHomomorphicInt` for the same computational cost as currently.

**Comment by ineiti** [comment]
Yes, that should work. If you have a project where you need a greater `MaxHomomorphicInt`, this might be worth it. Although I have no idea how much you can increase that value by using the bsgs-approach...
