### ISSUE TITLE
aggregationAnnoucementPhase in collective aggregation protocol

### ISSUE THREAD

**Issue by cgrigis** [ldsec/unlynx#36]
What is the purpose of the [aggregationAnnmoucementPhase](https://github.com/ldsec/unlynx/blob/master/protocols/collective_aggregation_protocol.go#L197-L205)? My understanding is that the nodes only pass down empty messages?

**Comment by JoaoAndreSa** [comment]
The idea is to spread an initialization message in a tree-like manner down from the root to the nodes  so they can start their protocol. This way the nodes can start doing their local computations knowing their parent node is up and running. @cgrigis you think we should do it differently?

**Comment by cgrigis** [comment]
I am not very familiar with how protocols are generally implemented in Onet, so I may be wrong. :)
I was just surprised by the fact that that phase does not propagate any actual information. What could go wrong if we did not have this phase?

**Comment by tharvik** [comment]
It should not be needed, as `ProtocolInstance.Dispatch` is called on every node when starting the protocol.

**Comment by JoaoAndreSa** [comment]
@tharvik I am not sure... For what I understood `ProtocolInstance.Dispatch` is called after the first message sent to a node. If, for example, I remove this `aggregationAnnouncementPhase()` the test does not work as is. The root just hangs in the `Start()` (and is the only one that executes the `Dispatch`)

**Comment by tharvik** [comment]
Ho, you're right, one still have a message for the protocol to begin; that's looks weird indeed

**Comment by ineiti** [comment]
If I understand it correctly, this is just the phase where the protocol is started and linked to the service of every node. If you don't do that, then
- the nodes will not be synchronized
- the nodes will not be able to use the same protocol-instance

Does that make sense?
